sudo: required
dist: trusty
language: go
go:
  - "1.11.x"
  - tip

install:
  - go get -t github.com/SkycoinProject/skyencoder/...
  - go install github.com/SkycoinProject/skyencoder/cmd/skyencoder

script:
  - make check
  - skyencoder -struct DemoStruct github.com/SkycoinProject/skyencoder/tests

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

